[project]
name        = "lbmstl-core"
version     = "0.1.0"
description = "Shared dataclasses & I/O for lbmstl toolchain"
readme      = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy>=1.23",
    "trimesh",        # for load_stl
]

[tool.setuptools.packages.find]
where = ["src"]